image: alpine/helm

stages:
  - deploy
  - cleanup
  - merge

before_script:
  - helm repo add kong https://charts.konghq.com
  - helm repo update

.variables: &variables
  APP: $CI_PROJECT_NAME

.deploy: &deploy
  stage: deploy
  tags:
    - gitlab-runner
  allow_failure: false
  script:
    - >
      helm upgrade -i -n $NAMESPACE -f values.yaml $APP kong/kong
      --set ingressController.ingressClass=$INGRESS_CLASS
      --set ingressController.watchNamspaces={$NAMESPACE}
      --set proxy.ingress.hostname=$APP_HOST
      --wait --debug

.cleanup: &cleanup
  when: manual
  tags:
    - gitlab-runner
  allow_failure: false
  script:
    - helm -n $NAMESPACE uninstall $APP

dev:
  <<: *deploy
  environment:
    name: development
    url: https://$APP_HOST
  variables:
    <<: *variables
    NAMESPACE: dev
    APP_HOST: dev.$CLUSTER_DOMAIN
    INGRESS_CLASS: kong-dev
  only:
    - dev

prod:
  <<: *deploy
  environment:
    name: production
    url: https://$APP_HOST
  variables:
    <<: *variables
    NAMESPACE: prod
    APP_HOST: $CLUSTER_DOMAIN
    INGRESS_CLASS: kong-prod
  only:
    - main

stop-dev:
  <<: *cleanup
  stage: cleanup
  environment:
    name: development
    action: stop
  variables:
    <<: *variables
    NAMESPACE: dev
  only:
    - dev

stop-prod:
  <<: *cleanup
  stage: cleanup
  environment:
    name: production
    action: stop
  variables:
    <<: *variables
    NAMESPACE: prod
  only:
    - main



    

